### ISSUE TITLE
"Google Drive returned a fatal error" when running upload

### ISSUE THREAD

**Issue by JCarran0** [danthareja/node-google-apps-script#21]
I'm not able to run the upload for my project.  I successfully pulled down an existing (and working) project via gapps init, and when I immediately try to run the upload without changing any files I get the following error:

Google Drive returned a fatal error.
Error running upload command

My .gapps file looks correct, I have all necessary libraries added to the project, and running eslint on the project doesn't show any syntax errors.

**Comment by danthareja** [comment]
Hmm, these errors are always tricky to track down. Let me look into it a bit.

**Comment by hess-g** [comment]
I  got that when I initially loaded the new version, as I was using a new Google developer console project, and hadn't enabled the Drive API. 

Another scenario could be that you are uploading an empty file - you have to have at least one line with a  "//" comment if you want to upload a placeholder file; a single JavaDoc line will still throw the error.

That error also shows up if one of your files has javascript errors - basically anything that the Apps Script UI wouldn't let you save. Since you are linting already that probably isn't the issue.

**Comment by JCarran0** [comment]
I believe Drive API is correctly enabled.  It's not an empty file as it's an existing project with multiple files.  It can't be a syntax error because it passes the lining, but also because it's an existing project that runs fine from the Apps Script web interface.    

@danthareja  I can share my project if that helps with trouble shooting.

**Comment by hess-g** [comment]
I found a minor fix that was needed after the latest merge. PR coming...

**Comment by hess-g** [comment]
PR #22 is out. I'll let Dan review and merge.

**Comment by danthareja** [comment]
Just merged it in. @JCarran0 can you install `v1.1.3` and confirm that your issue is fixed?

**Comment by JCarran0** [comment]
Yes, it seems to be working correctly now!  Thanks @hess-g and @danthareja

**Comment by danthareja** [comment]
Cheers!
