### ISSUE TITLE
Error occurred while running upload command: null

### ISSUE THREAD

**Issue by davisg123** [danthareja/node-google-apps-script#24]
I get this error when attempting to upload my changes.

<img width="568" alt="screen shot 2015-11-22 at 2 46 23 pm" src="https://cloud.githubusercontent.com/assets/2341305/11325885/ee58aabe-9127-11e5-9bc9-35c3f31a7e5a.png">

Not very helpful, any ideas?

**Comment by danthareja** [comment]
Hmm, not helpful indeed. That error occurs when the request to Google Drive fails and could happen for many reasons.

Can you try reproducing the same error with another project? If that doesn't work, more information about this particular error might help. Right now I'm only logging the `message` property on the `error` object that comes back from google. Do you feel comfortable editing your local copy to log the entire error object? You should find this downloaded in `/usr/local/lib/node_modules`. You'll find the log on line 53 of `upload.js.

**Comment by davisg123** [comment]
Logging the entire error object also gives null.  I'll keep investigating.

**Comment by danthareja** [comment]
Sorry these ones can be really tricky to track down. Maybe try re-authenticating?

Please do let me know if you find anything more

**Comment by davisg123** [comment]
Figured it out. I wasn't using a standalone script, it was attached to a spreadsheet.

**Comment by danthareja** [comment]
Oh, excellent!

**Comment by huan** [comment]
it seems it's because some bug inside google-api-nodejs-client . I opened a issue over there.

**Comment by 0cjs** [comment]
If I understand correctly what the issue was here, it's not precisely a bug as much as a missing feature on the Google side: they make it quite clear that the API can only be used to access Apps Script projects, and that bound code in other types of documents is entirely inaccessible.

It also seems that this may indicate a bug in gapps where it doesn't check the MIME type of the document before it attempts to upload or download, to ensure that it's trying to access a document of the appropriate type.
